spring:
  application:
    name: com.knox.askgpt

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs.enabled: true

open-api:
  url:
    base-url: ${OPENAI_BASE_URL:https://api.openai.com}
    response: /v1/responses
  key: ${OPENAI_API_KEY:ADD-YOUR-KEY}
  model: ${OPENAI_MODEL:gpt-5.2}